export const S = {
  root: { fontFamily:"'DM Sans',sans-serif", background:"#f4f5f9", minHeight:"100vh", color:"#1a1a2e" },
  header: { background:"#1a1a2e", color:"#fff", padding:"0 14px" },
  headerInner: { display:"flex", alignItems:"center", justifyContent:"space-between", height:56 },
  brand: { display:"flex", alignItems:"center", gap:10 },
  brandName: { fontSize:16, fontWeight:700, letterSpacing:"-0.02em" },
  brandSub: { fontSize:10, color:"#4ade80", letterSpacing:"0.06em" },
  btnExport: { background:"transparent", border:"1px solid #4f46e5", color:"#818cf8", padding:"6px 12px", borderRadius:8, cursor:"pointer", fontSize:12, fontWeight:600 },
  nav: { background:"#fff", borderBottom:"1px solid #e5e7eb", padding:"0 4px", display:"flex", overflowX:"auto" },
  navBtn: { padding:"12px 11px", background:"none", border:"none", borderBottom:"3px solid transparent", color:"#6b7280", cursor:"pointer", fontWeight:600, fontSize:12, whiteSpace:"nowrap", fontFamily:"inherit" },
  navActive: { color:"#4f46e5", borderBottomColor:"#4f46e5" },
  main: { padding:"14px 12px 80px", maxWidth:700, margin:"0 auto" },
  pageTitle: { fontSize:18, fontWeight:800, color:"#1a1a2e", marginBottom:14, letterSpacing:"-0.02em" },
  groupLabel: { fontSize:11, fontWeight:700, color:"#9ca3af", textTransform:"uppercase", letterSpacing:"0.06em", marginBottom:8, marginTop:4 },
  kpiRow: { display:"grid", gridTemplateColumns:"1fr", gap:9, marginBottom:16 },
  kpi: { background:"#fff", borderRadius:12, padding:"12px 14px", display:"flex", alignItems:"center", gap:12, boxShadow:"0 1px 3px rgba(0,0,0,0.05)" },
  kpiIcon: { fontSize:18, width:38, height:38, borderRadius:10, background:"#f3f4f6", display:"flex", alignItems:"center", justifyContent:"center", flexShrink:0 },
  kpiVal: { fontSize:19, fontWeight:800, letterSpacing:"-0.03em", lineHeight:1 },
  kpiLabel: { fontSize:11, color:"#9ca3af", marginTop:3, fontWeight:500 },
  card: { background:"#fff", borderRadius:14, padding:"12px 14px 4px", marginBottom:14, boxShadow:"0 1px 3px rgba(0,0,0,0.05)" },
  accCard: { background:"#fff", borderRadius:14, padding:14, marginBottom:12, boxShadow:"0 1px 3px rgba(0,0,0,0.06)" },
  accCardTop: { display:"flex", alignItems:"flex-start", justifyContent:"space-between", marginBottom:12 },
  accName: { fontSize:14, fontWeight:700, color:"#1a1a2e" },
  badge: { fontSize:9, fontWeight:700, padding:"2px 6px", borderRadius:20, letterSpacing:"0.06em", display:"inline-block", marginTop:3 },
  infoBtn: { fontSize:17, color:"#c7d2fe", cursor:"pointer", background:"none", border:"none", padding:"0 2px" },
  tooltip: { background:"#1e293b", color:"#e2e8f0", fontSize:12, borderRadius:10, padding:"10px 12px", marginBottom:12, lineHeight:1.55 },
  statRow: { display:"flex", alignItems:"center", marginBottom:10 },
  statDiv: { width:1, height:30, background:"#f3f4f6" },
  miniTrack: { height:5, background:"#f3f4f6", borderRadius:4, overflow:"hidden", marginBottom:4 },
  miniFill: { height:"100%", borderRadius:4, transition:"width 0.5s ease" },
  miniLabel: { fontSize:10, color:"#9ca3af", textAlign:"right" },
  accDetailCard: { background:"#fff", borderRadius:14, padding:16, marginBottom:14, boxShadow:"0 1px 3px rgba(0,0,0,0.06)" },
  accDetailName: { fontSize:16, fontWeight:800, color:"#1a1a2e" },
  accDesc: { fontSize:13, color:"#6b7280", lineHeight:1.55, marginBottom:14, paddingBottom:14, borderBottom:"1px solid #f3f4f6" },
  viewBtn: { fontSize:12, fontWeight:700, background:"none", border:"1px solid", borderRadius:8, padding:"6px 12px", cursor:"pointer", fontFamily:"inherit" },
  filterCol: { display:"flex", flexDirection:"column", gap:8, marginBottom:12 },
  select: { width:"100%", padding:"10px 12px", borderRadius:8, border:"1px solid #e5e7eb", background:"#fff", fontSize:13, color:"#374151", fontFamily:"inherit", boxSizing:"border-box" },
  row: { display:"flex", alignItems:"center", gap:10, padding:"10px 0" },
  rowDot: { width:30, height:30, borderRadius:8, display:"flex", alignItems:"center", justifyContent:"center", fontWeight:700, fontSize:14, flexShrink:0 },
  rowTitle: { fontSize:13, fontWeight:600, color:"#1f2937", overflow:"hidden", textOverflow:"ellipsis", whiteSpace:"nowrap" },
  rowSub: { fontSize:11, color:"#9ca3af", marginTop:2, display:"flex", alignItems:"center", gap:4, overflow:"hidden", whiteSpace:"nowrap" },
  accTag: { fontSize:9, fontWeight:700, padding:"1px 5px", borderRadius:10, letterSpacing:"0.04em", flexShrink:0 },
  iconBtn: { background:"none", border:"none", color:"#9ca3af", cursor:"pointer", fontSize:14, padding:"4px 4px", borderRadius:6 },
  attPanel: { padding:"8px 12px 12px 48px", display:"flex", flexDirection:"column", gap:6 },
  attRow: { display:"flex", alignItems:"center", gap:8 },
  attLink: { fontSize:12, color:"#6366f1", textDecoration:"none", flex:1, overflow:"hidden", textOverflow:"ellipsis", whiteSpace:"nowrap" },
  formCard: { background:"#fff", borderRadius:16, padding:18, boxShadow:"0 1px 3px rgba(0,0,0,0.06)" },
  formTitle: { fontSize:18, fontWeight:800, marginBottom:18, color:"#1a1a2e", letterSpacing:"-0.03em" },
  label: { display:"block", fontSize:11, fontWeight:600, color:"#6b7280", marginBottom:5, textTransform:"uppercase", letterSpacing:"0.05em" },
  input: { width:"100%", padding:"10px 12px", borderRadius:9, border:"1px solid #e5e7eb", fontSize:14, fontFamily:"inherit", color:"#1f2937", background:"#f9fafb", boxSizing:"border-box" },
  accChip: { flex:1, padding:"9px 4px", borderRadius:9, cursor:"pointer", fontWeight:700, fontSize:11, fontFamily:"inherit" },
  chipDesc: { fontSize:11, color:"#9ca3af", lineHeight:1.5, padding:"6px 10px", background:"#f9fafb", borderRadius:8 },
  fileLabel: { display:"block", padding:"10px 12px", borderRadius:9, border:"2px dashed #e5e7eb", fontSize:13, color:"#6b7280", textAlign:"center", cursor:"pointer", background:"#f9fafb" },
  fileChip: { display:"flex", alignItems:"center", gap:8, padding:"6px 10px", background:"#f3f4f6", borderRadius:8, marginBottom:4, fontSize:12 },
  fileChipDel: { background:"none", border:"none", color:"#9ca3af", cursor:"pointer", fontSize:13, padding:0, flexShrink:0 },
  btnCancel: { padding:"10px 16px", borderRadius:9, border:"1px solid #e5e7eb", background:"#fff", cursor:"pointer", fontWeight:600, fontSize:13, fontFamily:"inherit" },
  btnSave: { padding:"10px 22px", borderRadius:9, border:"none", color:"#fff", cursor:"pointer", fontWeight:700, fontSize:13, fontFamily:"inherit" },
  fbCard: { background:"#fff", borderRadius:12, padding:14, marginBottom:10, boxShadow:"0 1px 3px rgba(0,0,0,0.05)" },
  fbType: { fontSize:12, fontWeight:700, color:"#374151" },
  fbWho: { fontSize:12, color:"#9ca3af" },
  fbStatus: { fontSize:10, fontWeight:700, padding:"2px 8px", borderRadius:20 },
  toast: { position:"fixed", bottom:24, left:"50%", transform:"translateX(-50%)", color:"#fff", padding:"10px 22px", borderRadius:10, fontWeight:600, fontSize:13, zIndex:999, boxShadow:"0 4px 12px rgba(0,0,0,0.2)", whiteSpace:"nowrap" },
};
